title: Comparing Landscapes - Approaches to Space and Affect in Literary Fiction
# theme: jekyll-theme-cayman
remote_theme: just-the-docs/just-the-docs
description: April 20-21 2023, Bielefeld University, Germany
