remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Comparing Landscapes: Approaches to Space and Affect in Literary Fiction"
logo: mountain_vs_city_kirchner.png
description: "Ernst Ludwig Kirchner (1880-1938)"
